processors:
  batch:
    # Optional: you can tune these, but defaults are usually fine
    send_batch_size: 1000
    timeout: 200ms

receivers:
  otlp:
    protocols:
      http: # Spring Boot starter uses HTTP by default
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp_grpc:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  debug: # This will print METRICS to your terminal logs instead of Jaeger
    verbosity: basic



service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp_grpc, debug ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug ]
