spring:
  application:
    name: ice-metadata

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    io.opentelemetry: DEBUG
    io.opentelemetry.exporter: DEBUG
    io.micrometer.tracing: DEBUG

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
  metrics:
    exporter: otlp
  traces:
    exporter: otlp
    sampler: always_on

