CREATE TABLE IF NOT EXISTS TRACK_METADATA (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255),
    ARTIST_ID VARCHAR(255)
);
CREATE INDEX IF NOT EXISTS IDX_ARTIST_ID ON TRACK_METADATA(ARTIST_ID);




