CREATE TABLE IF NOT EXISTS ARTIST_ALIAS (
    ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION TEXT,
    USER_ID VARCHAR(255),
    VERSION BIGINT NOT NULL DEFAULT 0
    );
CREATE INDEX IF NOT EXISTS IDX_USER_ID ON ARTIST_ALIAS(USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_NAME ON ARTIST_ALIAS(NAME);